version: '3.8'

services:
  router:
    build: ./ml-router
    ports:
      - "5001:5001"

  orchestrator:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - router
    volumes:
      # Links the dashboard for the UI
      - ./dashboard:/usr/src/app/dashboard
      # NEW: Links the entire local logs directory into the container
      - ./logs:/usr/src/app/logs